# Sử dụng Redis image chính thức từ Docker Hub
FROM redis:latest

# Mô tả thông tin người tạo image
LABEL maintainer="Your Name <your.email@example.com>"

# Mở cổng 6379 để có thể kết nối đến Redis
EXPOSE 6379

# Có thể thêm các tùy chọn cấu hình khác tại đây nếu cần thiết

# Lệnh CMD để chạy khi container được khởi chạy
CMD ["redis-server"]
